"""
Gate-level simulation of a netlist (via HAL's netlist_simulator_controller +
the verilator engine) driven directly from a real VCD stimulus file, so the
reconstructed netlist's O/success outputs can be checked against known-good
recorded values.

Run inside HAL's own embedded Python interpreter:
  ./bin/hal --python-script scripts/simulate_vs_vcd.py \
    --py-args "<netlist.v> <liberty.lib> <stimulus.vcd> <out.vcd>"
"""
import sys
import hal_py

if len(sys.argv) != 4:
    print("usage: --python-script simulate_vs_vcd.py --py-args \"<netlist.v> <liberty.lib> <stimulus.vcd> <out.vcd>\"")
    sys.exit(1)
NETLIST, LIBERTY, VCD, OUT_VCD = sys.argv[0], sys.argv[1], sys.argv[2], sys.argv[3]

nl = hal_py.NetlistFactory.load_netlist(NETLIST, LIBERTY)
if nl is None:
    print("FAILED TO LOAD NETLIST")
    sys.exit(1)

# Captured once, up front, and reused below - calling
# get_global_input_nets()/get_global_output_nets() again later (after
# create_simulation_engine()/run_simulation() have touched the netlist via
# the verilator engine's subgraph-copy/rewrite machinery) crashed with
# "TypeError: 'hal_py.PinType' object is not callable" (confirmed directly,
# not yet root-caused - avoiding the second call sidesteps it entirely).
global_input_nets = list(nl.get_global_input_nets())
global_output_nets = list(nl.get_global_output_nets())

from hal_plugins import netlist_simulator_controller as nsc

pl = hal_py.plugin_manager.get_plugin_instance("netlist_simulator_controller")
sim = pl.create_simulator_controller("puzzle_sim")

sim.add_gates(nl.get_gates())
print("engines available:", sim.get_engine_names())
print("controller input_nets:", [n.name for n in sim.get_input_nets()])
print("controller output_nets:", [n.name for n in sim.get_output_nets()])
print("netlist global inputs:", [n.name for n in global_input_nets])
print("netlist global outputs:", [n.name for n in global_output_nets])

# clk is driven directly from the VCD stimulus (import_vcd below), not
# generated by the controller's own add_clock_period()/add_clock_frequency()
# - without telling it that explicitly, SimulationInput::is_ready() stays
# false forever (it requires either a registered clock or this flag) and
# run_simulation() refuses to run ("wrong state").
sim.set_no_clock_used()

engine = sim.create_simulation_engine("verilator")
if engine is None:
    print("FAILED to create verilator simulation engine")
    sys.exit(1)

ok = sim.import_vcd(VCD, nsc.FilterInputFlag.GlobalInputs)
print("import_vcd ok:", ok)
print("max simulated time after import (ps):", sim.get_max_simulated_time())
if not ok:
    sys.exit(1)

ok2 = sim.run_simulation()
print("run_simulation ok:", ok2)
if not ok2:
    sys.exit(1)

max_t = sim.get_max_simulated_time()
print("max simulated time (ps):", max_t)

# generate_vcd() only ever writes nets already present in the controller's
# internal WaveDataList; add_gates() only seeds that list with INPUT nets
# (confirmed directly: an empty "nets" arg wrote just clk/enable/rst_n/I/
# VPWR/VGND, silently dropping every output). get_waveform_by_net() lazily
# pulls a net's simulated result into that list as a side effect - call it
# for every output net first so generate_vcd() actually has them to write.
for n in global_output_nets:
    sim.get_waveform_by_net(n)

# No explicit "nets" arg: pybind's binding requires an actual Python
# Set[hal_py.Net] here (a plain list is rejected), but constructing a
# Python set out of hal_py.Net objects crashes with "TypeError:
# 'hal_py.PinType' object is not callable" (confirmed directly - Net's
# __hash__ binding is broken in this build, so set()/{...} can't be used
# on Net objects at all). Sidestepped entirely by relying on the default
# empty-set behavior instead, which just dumps everything already in the
# controller's own WaveDataList - inputs were seeded there by add_gates(),
# and the get_waveform_by_net() calls above already pulled every output's
# result in too, so nothing is actually missing.
ok3 = sim.generate_vcd(OUT_VCD, 0, max_t)
print("generate_vcd ok:", ok3, "->", OUT_VCD)
